# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FluidCash' do
pod 'ObjectMapper', '~> 1.0'

use_frameworks!
end

target 'FluidCashTests' do

end

target 'FluidCashUITests' do

end

